FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"

RUN pip install --no-cache-dir -r requirements.txt

COPY . .